"""All Russian UI texts of the web panel (the single texts module of the web layer).

Templates read them as ``t.<key>`` (Jinja ``StrictUndefined``: a missing key is an error);
Python code uses ``T["<key>"]``.
"""

from __future__ import annotations

T: dict[str, str] = {
    # generic
    "app_name": "Панель прокси",
    "yes": "да",
    "no": "нет",
    "any": "любые",
    "ok": "работает",
    "fail": "сбой",
    "no_data": "Нет данных",
    "details": "подробности",
    "open": "открыть",
    "save": "Сохранить",
    "saved": "Сохранено",
    "add": "Добавить",
    "remove": "Удалить",
    "run": "Выполнить",
    "copy": "Копировать",
    "hide": "Скрыть",
    "reset": "Сбросить",
    "prev": "Назад",
    "next": "Далее",
    "days": "дней",
    "days_short": "дн.",
    "preview": "Предпросмотр",
    "to_home": "На главную",
    "error_title": "Ошибка",
    "nothing_changed": "Ничего не изменилось",
    "operation_failed": "Операция не выполнена",
    "applying": "Применяются изменения, подождите…",
    "last_apply_failed": "Последнее применение изменений завершилось сбоем",
    "bot_unavailable": "Бот сейчас недоступен",
    "traffic_unavailable": "Данные о трафике недоступны",
    "not_found": "Не найдено",
    "http_error": "Ошибка запроса",
    "bad_request": "Некорректный запрос",
    "server_error": "Внутренняя ошибка сервера",
    "csrf_failed": "Недействительный токен формы. Обновите страницу и повторите.",
    "bad_number": "Некорректное число",
    "bad_date": "Некорректная дата",
    "bad_filter": "Некорректное значение фильтра",
    "bad_sort": "Недопустимое поле сортировки",
    "file_too_big": "Файл слишком большой",
    "too_many": "Слишком много пользователей (максимум {limit})",
    # navigation
    "nav_dashboard": "Дашборд",
    "nav_users": "Пользователи",
    "nav_create": "Создать",
    "nav_import": "Импорт",
    "nav_requests": "Заявки",
    "nav_broadcast": "Рассылка",
    "nav_settings": "Настройки",
    "nav_backups": "Бэкапы",
    "nav_audit": "Журнал",
    "logout": "Выйти",
    "logout_all": "Завершить все сессии",
    # login
    "login_title": "Вход",
    "login_user": "Логин",
    "login_password": "Пароль",
    "login_submit": "Войти",
    "login_failed": "Неверный логин или пароль",
    "login_throttled": "Слишком много попыток входа. Повторите через {seconds} с.",
    "login_token_bad": "Форма устарела. Обновите страницу и повторите.",
    # dashboard
    "dashboard_degraded": "Подробная статистика недоступна, показаны только базовые счётчики.",
    "dash_users": "Пользователи",
    "dash_active": "активных",
    "dash_online": "онлайн",
    "dash_disabled": "выключено",
    "dash_expired": "истекло",
    "dash_traffic_24h": "Трафик за 24 часа",
    "dash_traffic_30d": "Трафик за 30 дней",
    "dash_capacity": "Ёмкость",
    "dash_pool": "Пул",
    "dash_sessions": "Сессии relay (сейчас / лимит)",
    "dash_limit_hits": "Срабатываний лимитов",
    "dash_health": "Здоровье",
    "dash_relay": "Relay",
    "dash_cert": "Сертификат панели, осталось",
    "dash_cert_warn": "автопродление не работает?",
    # table columns
    "col_id": "№",
    "col_display_name": "Имя",
    "col_name": "Профиль",
    "col_comment": "Комментарий",
    "col_tg_id": "Telegram ID",
    "col_tg_username": "Username",
    "col_status": "Статус",
    "col_online": "Онлайн",
    "col_created_at": "Создан",
    "col_expires_at": "Срок действия",
    "col_first_seen_at": "Первое соединение",
    "col_last_seen_at": "Последняя активность",
    "col_traffic": "Трафик",
    "col_pool_id": "Пул",
    "col_bot_started": "Бот запущен",
    "col_time": "Время",
    "col_finished": "Завершено",
    "col_reason": "Причина",
    "col_actor": "Кто",
    "col_action": "Действие",
    "col_target": "Объект",
    "col_details": "Детали",
    "col_error": "Ошибка",
    "status_active": "активен",
    "status_disabled": "выключен",
    "status_expired": "истёк",
    "no_expiry": "бессрочно",
    # users list
    "f_search": "Поиск (имя, комментарий, ID, username)",
    "f_online": "Онлайн",
    "f_imported": "Импортированные",
    "f_tg": "С Telegram ID",
    "f_bot": "Бот запущен",
    "f_expires_days": "Истекает в ближайшие, дней",
    "f_created_from": "Создан с",
    "f_created_to": "Создан по",
    "f_seen_from": "Активность с",
    "f_seen_to": "Активность по",
    "f_traffic_min": "Трафик больше, МБ",
    "f_traffic_max": "Трафик меньше, МБ",
    "f_comment": "Комментарий содержит",
    "f_period": "Период трафика",
    "f_per_page": "На странице",
    "period_24h": "24 часа",
    "period_7d": "7 дней",
    "period_30d": "30 дней",
    "period_all": "всё время",
    "apply_filters": "Применить",
    "columns": "Колонки",
    "select_page": "Выбрать на странице",
    "select_matching": "Выбрать всё по фильтру ({n})",
    "bulk_action": "Массовое действие",
    "bulk_none": "Ничего не выбрано",
    "bulk_changed": "Выборка изменилась с момента показа списка. Повторите действие.",
    "act_send_link": "Отправить ссылку",
    "act_enable": "Включить",
    "act_disable": "Выключить",
    "act_extend": "Продлить",
    "act_set_comment": "Изменить комментарий",
    "act_delete": "Удалить",
    "act_clear_expiry": "Снять срок",
    "act_set_expiry": "Установить срок",
    "act_carrier": "Сменить carrier_mode",
    "act_reissue": "Перевыпустить секрет",
    "reveal_links": "Показать ссылки",
    "done_n": "Готово: {n}",
    "deleted_n": "Удалено пользователей: {n}",
    "deleted": "Пользователь удалён",
    "delete_word": "удалить",
    "delete_confirm_bad_bulk": "Для удаления введите слово «{word}»",
    "delete_type_name": "Введите имя профиля для подтверждения",
    "delete_name_mismatch": "Имя профиля введено неверно, удаление отменено",
    "links_sent": "Ссылки отправлены: {sent}, не удалось: {failed}.",
    "link_sent": "Ссылка отправлена",
    "link_delivered": "отправлена",
    "delivery_error": "ошибка доставки",
    "create_send_link": "Отправить ссылку пользователю в Telegram (если указан Telegram ID)",
    "col_delivery": "Доставка в Telegram",
    # card
    "access": "Доступ",
    "reveal": "Показать ссылку",
    "reveal_all": "Показать все ссылки",
    "link_https": "Ссылка https",
    "link_tg": "Ссылка tg://",
    "secret": "Секрет",
    "traffic": "Трафик",
    "up": "вверх",
    "down": "вниз",
    "total": "всего",
    "actions": "Действия",
    "events": "События",
    "imported": "Импортирован",
    "carrier": "carrier_mode",
    "carrier_default": "по умолчанию",
    "reissue_confirm": "Понимаю: старая ссылка перестанет работать",
    "reissue_confirm_needed": "Подтвердите перевыпуск секрета",
    "reissued": "Секрет перевыпущен",
    # create
    "create_mode": "Режим",
    "create_single": "Один пользователь",
    "create_count": "Пакет по количеству",
    "create_list": "Пакет по списку",
    "create_prefix": "Префикс имени (для пакета)",
    "create_number": "Количество",
    "create_list_label": (
        "Список: «имя профиля; telegram id; комментарий; имя», по строке на пользователя "
        "(telegram id, комментарий и имя необязательны)"
    ),
    "create_display_name": "Имя (необязательно; для пакета по количеству к нему добавляется номер)",
    "bad_display_name": "Имя не длиннее 100 символов, в одну строку",
    "create_line_badname": "Строка {n}: некорректное имя",
    "create_submit": "Создать",
    "create_wait_hint": (
        "Страница дождётся применения изменений; ссылки доступны только после успеха."
    ),
    "create_noname": "Укажите имя",
    "create_noprefix": "Укажите префикс имени",
    "create_badcount": "Количество должно быть от 1 до {limit}",
    "create_emptylist": "Список пуст",
    "create_line_noname": "Строка {n}: нет имени",
    "create_line_badid": "Строка {n}: некорректный Telegram ID",
    "created_title": "Пользователи созданы",
    "created_ok": "Создано пользователей: {n}",
    "term": "Срок",
    "term_default": "по умолчанию из настроек",
    "term_1d": "1 день",
    "term_1m": "1 месяц",
    "term_1y": "1 год",
    "term_date": "конкретная дата",
    "term_date_label": "Дата (для «конкретная дата»)",
    # import
    "import_stop_old_bot": (
        "Прежний бот должен быть остановлен: иначе он перезапишет profiles.json своей версией."
    ),
    "import_regex": "Выражение для Telegram ID из имени профиля",
    "import_csv_text": "CSV: имя_профиля;telegram_id;имя;комментарий",
    "import_csv_file": "или файл CSV",
    "import_preview": "Показать предпросмотр",
    "import_preview_title": "Предпросмотр импорта",
    "import_source": "Исходное имя",
    "import_address": "Адрес",
    "import_skip": "Пропустить",
    "import_skipped": "пропущен",
    "import_new_pool": "новый пул",
    "import_will": "Будет импортировано: {n}",
    "import_recalc": "Пересчитать",
    "import_confirm": "Подтвердить импорт",
    "import_ack": "Прежний бот остановлен",
    "import_ack_needed": "Подтвердите, что прежний бот остановлен",
    "import_bad_tg": "{name}: некорректный Telegram ID",
    "import_semicolon": "{name}: символ «;» в именах недопустим",
    "import_done": "Импортировано: {imported}, пропущено: {skipped}",
    # requests
    "requests_pending": "Ожидают решения",
    "requests_history": "Решённые",
    "approve": "Одобрить",
    "reject": "Отклонить",
    "decided_by": "Решил",
    "request_approved": "Заявка одобрена",
    "request_rejected": "Заявка отклонена",
    # broadcast
    "broadcast_audience": "Получатели",
    "audience_active": "Активные пользователи с запущенным ботом",
    "audience_all": "Все пользователи с запущенным ботом",
    "broadcast_template": "Шаблон сообщения",
    "broadcast_placeholders": (
        "Подстановки: {name}, {link}, {expires}. Пустое значение — шаблон по умолчанию."
    ),
    "broadcast_recipients": "Выбрано",
    "broadcast_sendable": "Можно отправить",
    "broadcast_skipped": "Исключено",
    "broadcast_send": "Отправить рассылку",
    "broadcast_bad_form": "Выберите получателей и заполните шаблон (до 3500 символов)",
    "broadcast_nobody": "Нет получателей",
    "broadcast_report": "Отчёт о рассылке",
    "report_total": "всего",
    "report_sent": "отправлено",
    "report_failed": "ошибок",
    "report_result": "Результат",
    # settings
    "settings_proxy_note": "перезапустит relay",
    "settings_admins": "Администраторы бота",
    "settings_bot_token": "Токен бота",
    "settings_templates": "Шаблоны сообщений",
    "settings_password": "Пароль панели",
    "issuance_approval": "по одобрению",
    "issuance_open": "всем сразу",
    "token_set": "Токен задан (значение скрыто).",
    "token_unset": "Токен не задан.",
    "token_placeholder": "Новый токен",
    "token_bad": "Токен имеет неверный формат",
    "token_saved_restarted": "Токен сохранён, бот перезапущен с новым токеном",
    "token_saved_manual": "Токен сохранён, но бот не перезапущен: перезапустите службу",
    "password_reenter": "Пароль панели",
    "download_busy": "Уже идёт другое скачивание бэкапа. Повторите позже.",
    "download_hint": (
        "Архив содержит файл окружения и все секреты: для скачивания и восстановления "
        "нужно снова ввести пароль панели."
    ),
    "logout_all_short": "завершить все сессии",
    "logout_hint": (
        "Без галочки закрывается только эта сессия в этом браузере; "
        "в других браузерах вход сохраняется до истечения срока"
    ),
    "token_restart_hint": (
        "Токен записывается в файл окружения (не в базу данных) "
        "и применится после перезапуска бота."
    ),
    "bad_username": "Username: 5-32 символа, латиница, цифры и «_», начинается с буквы",
    "clear_tg_id": "Отвязать Telegram ID",
    "expiry_past_confirm": "Дата в прошлом: поставьте отметку подтверждения",
    "expiry_past_label": "дата в прошлом - подтверждаю",
    "broadcast_token_used": (
        "Форма устарела или рассылка уже запущена. Сделайте предпросмотр заново."
    ),
    "body_too_big": "Слишком большой запрос",
    "template_bad": "Шаблон слишком длинный или содержит секрет",
    "tpl_link": "Сообщение со ссылкой",
    "tpl_welcome": "Приветствие",
    "tpl_approved": "Заявка одобрена",
    "tpl_rejected": "Заявка отклонена",
    "tpl_expiring": "Напоминание об окончании срока",
    "tpl_expired": "Срок истёк",
    "tpl_broadcast": "Рассылка по умолчанию",
    "password_current": "Текущий пароль",
    "password_new": "Новый пароль",
    "password_again": "Повторите новый пароль",
    "password_change": "Сменить пароль",
    "password_wrong": "Текущий пароль неверен",
    "password_short": "Пароль должен быть не короче {n} символов",
    "password_mismatch": "Пароли не совпадают",
    "password_changed": "Пароль изменён, остальные сессии завершены",
    # backups
    "backup_create": "Создать полный бэкап",
    "backup_created": "Бэкап создан",
    "backup_size": "Размер",
    "download": "Скачать",
    "restore": "Восстановить",
    "restore_word": "восстановить",
    "restore_confirm_bad": "Для восстановления введите слово «{word}»",
    "restore_hint": (
        "Восстановление выполняется тем же конвейером применения с откатом при сбое; "
        "после него все сессии завершаются и нужно войти заново."
    ),
    "restored": "Состояние восстановлено",
    # audit
    "tab_audit": "Аудит",
    "tab_apply": "История применений",
    # redesign
    "menu": "Меню",
    "theme": "Тема",
    "theme_toggle": "Переключить светлую и тёмную тему",
    "online": "онлайн",
    "offline": "не в сети",
    "found": "Найдено",
    "more_filters": "Ещё фильтры",
    "selected": "Выбрано:",
    "select_row": "Выбрать: {name}",
    "pages": "Страницы",
    "loading": "Загрузка…",
    "card_profile": "Профиль",
    "card_info": "Сведения",
    "show_all_online": "показать всех онлайн",
    "dash_slots": "Слоты пулов",
    "dash_free": "свободно",
    "metrics_title": "Сервер",
    "metric_cpu": "Процессор",
    "metric_load": "нагрузка",
    "metric_cores": "ядер",
    "metric_memory": "Память",
    "metric_disk": "Диск",
    "metric_network": "Сеть",
    "metric_net_hint": "скорость за последние секунды",
    "metric_uptime": "Работает",
    "server_traffic": "Трафик сервера",
    "preset_1d": "1 день",
    "preset_7d": "7 дней",
    "preset_30d": "30 дней",
    "online_now": "Сейчас онлайн",
    "online_none": "Сейчас никого нет в сети",
    "online_traffic_hint": "Трафик за последние 24 часа.",
}
